/*
 * QroTerritoryService API
 * API REST para consultar el catálogo de delegaciones municipales de Querétaro y sus colonias asociadas. Permite que otros sistemas y aplicaciones obtengan dinámicamente la lista de colonias de una delegación, facilitando la integración en formularios de captura de direcciones (por ejemplo, al seleccionar una delegación se llena automáticamente el campo de colonia).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: l22140248@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tecnm.qro.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tecnm.qro.api.model.TipoAsentamiento;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * ColoniaInput
 */
@JsonPropertyOrder({
  ColoniaInput.JSON_PROPERTY_NOMBRE,
  ColoniaInput.JSON_PROPERTY_CODIGO_POSTAL,
  ColoniaInput.JSON_PROPERTY_TIPO_ASENTAMIENTO,
  ColoniaInput.JSON_PROPERTY_DELEGACION_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-20T01:52:00.215859711Z[Etc/UTC]")
public class ColoniaInput {
  public static final String JSON_PROPERTY_NOMBRE = "nombre";
  private String nombre;

  public static final String JSON_PROPERTY_CODIGO_POSTAL = "codigo_postal";
  private String codigoPostal;

  public static final String JSON_PROPERTY_TIPO_ASENTAMIENTO = "tipo_asentamiento";
  private TipoAsentamiento tipoAsentamiento;

  public static final String JSON_PROPERTY_DELEGACION_ID = "delegacion_id";
  private Integer delegacionId;

  public ColoniaInput() { 
  }

  public ColoniaInput nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

   /**
   * Debe iniciar con letra mayúscula
   * @return nombre
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Pattern(regexp="^[A-ZÁÉÍÓÚÜÑ].*") @Size(min=2,max=150)
  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNombre() {
    return nombre;
  }


  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNombre(String nombre) {
    this.nombre = nombre;
  }


  public ColoniaInput codigoPostal(String codigoPostal) {
    this.codigoPostal = codigoPostal;
    return this;
  }

   /**
   * Get codigoPostal
   * @return codigoPostal
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Pattern(regexp="^\\d{5}$")
  @JsonProperty(JSON_PROPERTY_CODIGO_POSTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodigoPostal() {
    return codigoPostal;
  }


  @JsonProperty(JSON_PROPERTY_CODIGO_POSTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodigoPostal(String codigoPostal) {
    this.codigoPostal = codigoPostal;
  }


  public ColoniaInput tipoAsentamiento(TipoAsentamiento tipoAsentamiento) {
    this.tipoAsentamiento = tipoAsentamiento;
    return this;
  }

   /**
   * Get tipoAsentamiento
   * @return tipoAsentamiento
  **/
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_TIPO_ASENTAMIENTO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TipoAsentamiento getTipoAsentamiento() {
    return tipoAsentamiento;
  }


  @JsonProperty(JSON_PROPERTY_TIPO_ASENTAMIENTO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTipoAsentamiento(TipoAsentamiento tipoAsentamiento) {
    this.tipoAsentamiento = tipoAsentamiento;
  }


  public ColoniaInput delegacionId(Integer delegacionId) {
    this.delegacionId = delegacionId;
    return this;
  }

   /**
   * Get delegacionId
   * minimum: 1
   * @return delegacionId
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(JSON_PROPERTY_DELEGACION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDelegacionId() {
    return delegacionId;
  }


  @JsonProperty(JSON_PROPERTY_DELEGACION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelegacionId(Integer delegacionId) {
    this.delegacionId = delegacionId;
  }


  /**
   * Return true if this ColoniaInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColoniaInput coloniaInput = (ColoniaInput) o;
    return Objects.equals(this.nombre, coloniaInput.nombre) &&
        Objects.equals(this.codigoPostal, coloniaInput.codigoPostal) &&
        Objects.equals(this.tipoAsentamiento, coloniaInput.tipoAsentamiento) &&
        Objects.equals(this.delegacionId, coloniaInput.delegacionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, codigoPostal, tipoAsentamiento, delegacionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColoniaInput {\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    codigoPostal: ").append(toIndentedString(codigoPostal)).append("\n");
    sb.append("    tipoAsentamiento: ").append(toIndentedString(tipoAsentamiento)).append("\n");
    sb.append("    delegacionId: ").append(toIndentedString(delegacionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `nombre` to the URL query string
    if (getNombre() != null) {
      joiner.add(String.format("%snombre%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNombre()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `codigo_postal` to the URL query string
    if (getCodigoPostal() != null) {
      joiner.add(String.format("%scodigo_postal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCodigoPostal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `tipo_asentamiento` to the URL query string
    if (getTipoAsentamiento() != null) {
      joiner.add(String.format("%stipo_asentamiento%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTipoAsentamiento()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `delegacion_id` to the URL query string
    if (getDelegacionId() != null) {
      joiner.add(String.format("%sdelegacion_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDelegacionId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

