/*
 * QroTerritoryService API
 * API REST para consultar el catálogo de delegaciones municipales de Querétaro y sus colonias asociadas. Permite que otros sistemas y aplicaciones obtengan dinámicamente la lista de colonias de una delegación, facilitando la integración en formularios de captura de direcciones (por ejemplo, al seleccionar una delegación se llena automáticamente el campo de colonia).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: l22140248@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tecnm.qro.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * Delegacion
 */
@JsonPropertyOrder({
  Delegacion.JSON_PROPERTY_ID,
  Delegacion.JSON_PROPERTY_NOMBRE,
  Delegacion.JSON_PROPERTY_SEDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-20T01:52:00.215859711Z[Etc/UTC]")
public class Delegacion {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NOMBRE = "nombre";
  private String nombre;

  public static final String JSON_PROPERTY_SEDE = "sede";
  private String sede;

  public Delegacion() { 
  }

  public Delegacion id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único
   * minimum: 1
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Integer id) {
    this.id = id;
  }


  public Delegacion nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

   /**
   * Nombre oficial
   * @return nombre
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNombre() {
    return nombre;
  }


  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNombre(String nombre) {
    this.nombre = nombre;
  }


  public Delegacion sede(String sede) {
    this.sede = sede;
    return this;
  }

   /**
   * Dirección
   * @return sede
  **/
  @jakarta.annotation.Nullable
 @Size(max=255)
  @JsonProperty(JSON_PROPERTY_SEDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSede() {
    return sede;
  }


  @JsonProperty(JSON_PROPERTY_SEDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSede(String sede) {
    this.sede = sede;
  }


  /**
   * Return true if this Delegacion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Delegacion delegacion = (Delegacion) o;
    return Objects.equals(this.id, delegacion.id) &&
        Objects.equals(this.nombre, delegacion.nombre) &&
        Objects.equals(this.sede, delegacion.sede);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombre, sede);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Delegacion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    sede: ").append(toIndentedString(sede)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nombre` to the URL query string
    if (getNombre() != null) {
      joiner.add(String.format("%snombre%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNombre()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sede` to the URL query string
    if (getSede() != null) {
      joiner.add(String.format("%ssede%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSede()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

