/*
 * QroTerritoryService API
 * API REST para consultar el catálogo de delegaciones municipales de Querétaro y sus colonias asociadas. Permite que otros sistemas y aplicaciones obtengan dinámicamente la lista de colonias de una delegación, facilitando la integración en formularios de captura de direcciones (por ejemplo, al seleccionar una delegación se llena automáticamente el campo de colonia).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: l22140248@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tecnm.qro.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TipoAsentamiento
 */
public enum TipoAsentamiento {
  
  FRACCIONAMIENTO("FRACCIONAMIENTO"),
  
  BARRIO("BARRIO"),
  
  COLONIA("COLONIA"),
  
  CONDOMINIO("CONDOMINIO"),
  
  UNIDAD_HABITACIONAL("UNIDAD_HABITACIONAL"),
  
  PUEBLO("PUEBLO"),
  
  EJIDO("EJIDO"),
  
  ZONA_INDUSTRIAL("ZONA_INDUSTRIAL"),
  
  ZONA_COMERCIAL("ZONA_COMERCIAL"),
  
  EQUIPAMIENTO("EQUIPAMIENTO"),
  
  RANCHERIA("RANCHERIA");

  private String value;

  TipoAsentamiento(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TipoAsentamiento fromValue(String value) {
    for (TipoAsentamiento b : TipoAsentamiento.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

